AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 37

Metrics/ClassLength:
  Max: 350

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 69

Metrics/ModuleLength:
  Max: 150

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
